### ISSUE TITLE
U8.shl broken

### ISSUE THREAD

**Issue by jacereda** [HigherOrderCO/Kind#110]
Looks like this should use `&0xFF` instead.

https://github.com/moonad/Formality/blob/31c34096c4598524d340c0ca103596362b99dd32/javascript/FormalityToJS.js#L156

**Comment by VictorTaelin** [comment]
Good catch. The JS compiler was moved to: https://github.com/moonad/FormCoreJS/blob/master/FmcToJs.js though. We must open that PR and fix it there.

**Comment by rigille** [comment]
i included that bug fix in this PR
https://github.com/moonad/FormCoreJS/pull/3
