### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by MaisaMilena** [HigherOrderCO/Kind#118]
### Bits
- [x] Bits.add - Bukzor
- [x] Bits.sub - jonathanrlouie 
- [x] Bits.mul - jonathanrlouie 
- [x] Bits.div
- [x] Bits.mod

### Word
- [x] Word.mul
- [x] Word.and
- [x] Word.div - elmattic
- [x] Word.mod - elmattic
- [x] Word.pow - elmattic
- [x] Word.shift_left
- [x] Word.shift_right
- [x] Word.or

### F64
- [ ] F64.add
- [ ] F64.mul
- [ ] F64.div
- [ ] F64.mod
- [ ] F64.pow
- [ ] F64.cmp
- [ ] F64.exp
- [ ] F64.log
- [ ] F64.max
- [ ] F64.min
- [ ] F64.exp
- [ ] F64.parse
- [ ] F64.sin
- [ ] F64.tan
- [ ] F64.to_u32

### Pos32
- [x] Pos32.dot - jonathanrlouie

### String
- [ ] String.replace

**Comment by Siddhant-K-code** [comment]
what are the remaining TODOs here, I saw almost all of the `bits` had already completed?

**Comment by MaisaMilena** [comment]
Hi @Siddhant-K-code ! I just updated the list. Bits are complete.

**Comment by Siddhant-K-code** [comment]
> Hi @Siddhant-K-code ! I just updated the list. Bits are complete.

hello, how can I start contributing with *Word*?

**Comment by MaisaMilena** [comment]
> > Hi @Siddhant-K-code ! I just updated the list. Bits are complete.
> 
> hello, how can I start contributing with _Word_?

Word is similar to Bits, but it contains a size attached to it: 
```
type Word ~ (size: Nat) {
  e                              ~ (size = Nat.zero),
  o<size: Nat>(pred: Word(size)) ~ (size = Nat.succ(size)),
  i<size: Nat>(pred: Word(size)) ~ (size = Nat.succ(size)),
}
```
This `size` is explained [here](https://github.com/uwu-tech/Kind/blob/master/SYNTAX.md#datatype). I think the better way to understand Word is taking a look at the existing code using it, like [`Word.or`](https://github.com/uwu-tech/Kind/blob/master/base/Word/or.kind). If you have any doubt you can also ask us on the [Telegram](https://t.me/formality_lang) group

**Comment by Siddhant-K-code** [comment]
i am working `Word.mod` and are your sure `Word.add` is completed?

**Comment by elmattic** [comment]
@Siddhant-K-code `Word.add` is completed yes. I am working on `Word.div` right now (using same algorithm than `Bits.div`), you will somewhat need it for `Word.mod`.

**Comment by Siddhant-K-code** [comment]
@elmattic can you pls tell me how to test for Word ( syntax example )

**Comment by elmattic** [comment]
Sure, we can talk of it on [Telegram](https://t.me/formality_lang).
