### ISSUE TITLE
Compiler is parsing incorrectly TypeXXX identifiers

### ISSUE THREAD

**Issue by elmattic** [HigherOrderCO/Kind#143]
```
type TypeIdx {
  new(value: U32)
}

Main: IO(Unit)
  do IO {
    let ty = TypeIdx.new(Nat.to_u32(0))
    //...
}
```

resulting in:

> Undefined reference: Idx.new
> Inside 'Main.kind':
>  255 | 
>  256 | Main: IO(Unit)
>  257 |   do IO {
>  258 |     let ty = Type**Idx.new**(Nat.to_u32(0))

```
base$ kind   
# Kind 1.0.4
```

**Comment by VictorTaelin** [comment]
Interesting, that could be solved by changing the parser to parse "Type " instead of "Type".

**Comment by elmattic** [comment]
TBH I don't understand the error because Kind is case sensitive.
