### ISSUE TITLE
Inconclusive type checker error message

### ISSUE THREAD

**Issue by Derenash** [HigherOrderCO/Kind#155]
A simple code to reproduce the error:

```
add(a: Nat, b: Nat): Nat
  case a
  { 
    zero: b
    succ: add(a.pred,Nat.succ(b))
  }

abc:_ 
add(3,4)
//comment
```

Get an error message of Expected letter in the code below it, but it doesn't explain the error.

The correct code cannot have a comment below the last line:

```
abc:_ 
add(3,4)
```

**Comment by rigille** [comment]
that's strange, in my machine the code typechecks. what version are you using?

**Comment by elmattic** [comment]
I have this error too with `Kind 1.0.26`. It looks like that if the last line in a file is a comment, then a newline must follow, otherwise the error `"Expected letter."` shows up.
