### ISSUE TITLE
Formality-core visualization?

### ISSUE THREAD

**Issue by mbuliga** [HigherOrderCO/Kind#17]
Hi Victor, do you need a js visualization for the formality-core? I just have one which can do interaction combinators [1] and it seems it is easy to adapt for your needs. As I am not competent in the intricacies of your project, I leave the link here. (Also I have to pay back for your nice questions on chemlambda.)

All is needed is to input the rewrite rules in obvious places and to feed the script with a network, presently done by adding it to molLib.js [2].

[1] https://mbuliga.github.io/find-the-quine-step-by-step.html

[2] https://github.com/mbuliga/mbuliga.github.io/blob/master/molLib.js

**Comment by VictorTaelin** [comment]
Sorry for he delay. I think a plenty of people worked on interaction net visualisations (seems like people love doing this!), but most projects end up abandoned as far as I know. It would be great to have one that is maintained! 

Thanks for your answers back then btw, it was very useful and important to me.

**Comment by johnchandlerburnham** [comment]
Oh, this is awesome! I did a little work on using GraphViz to layout an interaction net, but this seems like a much better approach. 

![image](https://user-images.githubusercontent.com/31078674/64220390-41c00e80-ce97-11e9-89b4-2e9180ebea05.png)

**Comment by mbuliga** [comment]
Thanks, yes, it can do Interaction Nets, adding nodes and rewrites for your system is simple, only thing needed is a parser to the mol notation. I use github with economy, any modification is first shown at http://imar.ro/~mbuliga/pages.html

**Comment by ishanpm** [comment]
Hi, I'm the original creator of the program shown above. I recently made some changes which make it fairly simple to add new nodes and transitions. It probably wouldn't be too hard to extend it to include integer-labeled nodes and operations.
