### ISSUE TITLE
filled holes that aren't actually filled

### ISSUE THREAD

**Issue by rigille** [HigherOrderCO/Kind#178]
# expected behavior
given the program
```js
type Subset ~ (A: Type) {
  nat ~ (A = Nat)
  str ~ (A = String)
}

DummyFn<A: Type, Ev: Subset(A)>(x: A): A
  x

Test: Nat
  DummyFn!!(0)

Test0: String
  DummyFn!!("hi")

Test1: Int
  DummyFn!!(+1)
```
all terms should typecheck and run, except `Test1`.
# current behavior
all terms typecheck but as of `kind 1.0.32` neither `Test`, `Test0`, nor `Test1` get to compile or run.

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
