### ISSUE TITLE
equivalent redefinition of Bool changes results

### ISSUE THREAD

**Issue by rigille** [HigherOrderCO/Kind#188]
# expected behavior

in the program
```
type Bool {
  false
  true
}

Bool.and(x: Bool, y: Bool): Bool
  case x {
    false: Bool.false
    true: y
  }

Test: _
  Bool.show(Bool.and(Bool.true, Bool.false))
```
`Test` should be result in `"Bool.false"`

# current behavior

`Test` results in `"Bool.true"`

**Comment by VictorTaelin** [comment]
Redefining a type will mess up the type-checker, we must disable that and display an error when it is attempted.

**Comment by rigille** [comment]
agreed

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
