### ISSUE TITLE
hello.fm fails to compile

### ISSUE THREAD

**Issue by Erhannis** [HigherOrderCO/Kind#19]
I started the tutorial, ran `npm i -g formality-lang` (got `formality-lang@0.3.98`), wrote

```
import Base@0 open

main : Output
  print("Hello, world!")
```

into `hello.fm`, and ran `fm hello/main`.  I received the following output:

```
Downloading files to `fm_modules`. This may take a while...
[PARSE-ERROR]
[PARSE-ERROR]
[PARSE-ERROR]
ReferenceError: TextEncoder is not defined

I noticed the problem on line 12, col 25:
   5|
   6| import Data.List@0 open
   7| import Data.Maybe@0 open
   8| import Data.Maybe.Control@0 open
   9| import Data.Nat@0 open
  10| import Data.Or@0 open
  11| import Data.String@0 open
  12| import Data.Unit@0 open                      --red line
  13| import Data.Vector2D@0 open
  14|
But it could have happened a little earlier.
If this is hard, consider relaxing. You deserve it!

I noticed the problem on line 4, col 0:
   1| import Algebra@0 as Algebra                      --red line
   2| import Control@0 as Control
   3| import Data@0 as Data
   4| import Induction@0 as Induction                      --red line
   5| import Logic@0 as Logic
   6|
But it could have happened a little earlier.
It takes me some time to process things. Have patience with me!

I noticed the problem on line 1, col 18:
   1| import Base@0 open                      --red line
   2|
   3| main : Output
   4|   print("Hello, world!")
But it could have happened a little earlier.
It takes me some time to process things. Have patience with me!
```

(`--red line` added by me to indicate red lines)

Is there a library that wasn't packaged right, or something?

I'm on Windows 10.

(By the way, the randomized flavor text at the bottom of each error chunk was funny for a second or two, but almost immediately became annoying.  It distracts from the actual data.  If you want to keep it, I'd recommend at least restricting it to once per run, and putting it somewhere out of the thick of things, like right after the error is named.)

**Comment by Erhannis** [comment]
Tried it on Ubuntu, on a different computer.  Approximately same result, though one of the source files looks slightly different.

**Comment by LoPoHa** [comment]
TextEncoder should come from Node.
If i remember correctly, i had a similar error with node 10 (on nixos though).
But with Node 12 everything worked.

**Comment by MaisaMilena** [comment]
@Erhannis let me know if the problem still happens after updating Node as @LoPoHa said

**Comment by Erhannis** [comment]
That fixed it.  Perhaps you could make a note on the installation page, about minimum Node version?

**Comment by johnchandlerburnham** [comment]
@Erhannis i've made an explicit note of the Node 12 dependency in the README in c1a54ba, will add to the docs repo as well.

@LoPoHa I made the Nix build a little simpler in 67023ff, using just `node2nix`, but since Node 12 isn't in stable `nixpkgs` yet you still need to build from `unstable`. I have a quick and dirty hack for this right now, but there ought to be a way to just tell `node2nix` to generate the expressions directly
