### ISSUE TITLE
Persistent cache breaks the checking

### ISSUE THREAD

**Issue by caotic123** [HigherOrderCO/Kind#195]
# Expect Behavior
Suppose code, code_aux, and my_dataype as kind files, where
  - my_dataype is just a file with a datatype definition
  - code_aux uses the my_datatype constructor.
  - code uses a definition of code_aux

Now consider all these files correctly, and check them in that order :
` my_datatype.kind --> code_aux.kind --> code.kind`
Finally, change the definition of my_datatype in some way that causes some type of error on code_aux.kind.
Checks code.kind, and it should give a type error.

# Current Behavior
Code.kind does not give a type error, even with code_aux being not typeable.

# How to reproduce :
Call the type checker in that order 
`Example.Test --> Example.Bugs.bug1_aux --> Example.Bugs.bug1.kind`
Now remove some field of the Test tuple.
For example, substitute the file to :
```
type Example.Test { 
   new(x : Bool)
 }
```
Now check Example.bugs.bug1, `kind Example.Bugs.bug1.kind`

**Comment by VictorTaelin** [comment]
This was the best bug report I ever received, nice job.
