### ISSUE TITLE
Documentation bug on `if`

### ISSUE THREAD

**Issue by Erhannis** [HigherOrderCO/Kind#20]
The documentation states

`if n: a else: b` | If `n .= 0`, evaluates to `a`, else, evaluates to `b`

According to the segment above that, `.=` means "equals".  So, if `n` equals `0`, `n` should effectively mean "true".  However, in testing:

`print(if 0: "0:true" else: "0:false")` prints `0:false`
`print(if 1: "1:true" else: "1:false")` prints `1:true`

which seems opposite what the documentation says.

**Comment by johnchandlerburnham** [comment]
Thanks! Fixed in https://github.com/moonad/docs.formality-lang.org/commit/946efe1ee444abadfdb86d7f42c21839ba16ea84

For avoidance of doubt:

```javascript
// TestIf.fm

import Base@0 open

condition : Word
  2 .< 3

test_if : String
  if condition: "true branch" else: "false branch"

main : [:Word, Output]
  [condition, print(test_if)]
```

Will output  `[1, true branch]` on `main`.

**Comment by Erhannis** [comment]
Hey, it looks like that commit did happen, but in merge commit https://github.com/moonad/docs.formality-lang.org/commit/37bad26d50a53efd701e6e087bd57b9b2ef36d73 many things were missed somehow, including this fix.

**Comment by Erhannis** [comment]
...Actually, I'm less certain about "many things" - GitEye shows only three files updated on merge, whereas the branch merged had 6 files changed.  However, Github shows 5 files changed on merge, so I'm not sure what's up, there.  Either way, the current documentation has the bug, again.

**Comment by johnchandlerburnham** [comment]
Fixed in https://github.com/moonad/docs.formality-lang.org/commit/f13dd5dd0994b1d4b21cdee2542a29a537aa1c68

I think the last fix just failed to propagate through the rename of that file. Thanks for catching it again though!

**Comment by Erhannis** [comment]
Yup, looks fixed, now.  Thanks!
