### ISSUE TITLE
Failed to install fm with proper permissions using npm

### ISSUE THREAD

**Issue by saolof** [HigherOrderCO/Kind#206]
When trying to run it after copy pasting the npm install command in powershell, I get:
```
PS C:\Users\olofs> fm
fm : File C:\Users\olofs\AppData\Roaming\npm\fm.ps1 cannot be loaded because running scripts is disabled on this
system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ fm
+ ~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by MaisaMilena** [comment]
you must install [`king-lang` package](https://www.npmjs.com/package/kind-lang) and use the command `kind`, not `fm`. Are you using Windows, right? You may face some issues running Kind on your machine if so. We recommend that you use [WSL](https://ubuntu.com/wsl) to assist you

**Comment by saolof** [comment]
Ah, I see the language has changed name. I was looking at the old formality repo. Sorry for the trivial question

**Comment by rigille** [comment]
no problem @saolof

**Comment by MaisaMilena** [comment]
@saolof the name of the language changed at the beginning of this year, not everyone may be familiar with that. Feel free to ask any question you have 😊
