### ISSUE TITLE
Open not working properly inside Monads

### ISSUE THREAD

**Issue by Sipher** [HigherOrderCO/Kind#210]
### Describe the bug
Using "open" syntax inside a Monad written function causes the compiler not to understand which argument its being reffered to.

### To Reproduce
1. Write the code on 'Test.kind'

```type Bug { 
  new(
    breaking: Broken,
    )
  }

type Broken { 
  new(
    not_working: Nat
  )
}

KindBug(bug: Broken): Maybe(Broken)
  some(bug)

Test:_

  let bug = Maybe {
    let Num = 1337
    let value = Bug.new(Broken.new(Num))
    open value
    get bug = KindBug(value.breaking)
    ?Argument
    }
  ?Answer
```

2. Use the command ' kind Test.kind '
  Using get instead of let on line 22 breaks the program

### Expected behavior
It should compile/type check, but since using get after an open inside a monad breaks the typecheck, it wont work

### Environment (please complete the following information):
 - OS: [iOS]
 - Kind version [kind@1.0.55]

### Additional context
Only tested with Types that has "new"as a constructor, and every argument inside the Type has another argument to it (Bug type as an example)

**Comment by VictorTaelin** [comment]
`log` is also not implemented inside monads. What else?

**Comment by racs4** [comment]
Sugar syntax for Pair Type also doesn't work
```
a: Pair<Int, Int>
  {2, 2}

Test:_
  let bug = Maybe {
    let {x, y} = a
    let num    = 1337
    return some(num)
  }
  bug
```

**Comment by VictorTaelin** [comment]
I think a monadic `for` would be nice too. Many syntaxes need a monadic counterpart. I wonder if `case`, `if` and similar should propagate it too?
