### ISSUE TITLE
"not" as a reserved word

### ISSUE THREAD

**Issue by MaisaMilena** [HigherOrderCO/Kind#214]
I was trying to create an alias in my code but realized that `not` is a reserved word, so I couldn't use it. Using alias can be helpful, improving the indentation and shortening functions with large names.

### To Reproduce
```
def and = U32.and // OK
def or    = U32.or   // OK
def not  = U32.not // error
```

`Bool.and` and `Bool.or` have syntax sugar using symbols, but not `not`. Maybe this is a case to review if using `not` as a reserved word is a good idea or should we consider a symbol, to make it similar to `and` and `or`.
.

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
