### ISSUE TITLE
Review documentation

### ISSUE THREAD

**Issue by MaisaMilena** [HigherOrderCO/Kind#22]
* [ ] Check code on `EA-TT`. It is different from the one we used on Gitlab.
* [ ] `FM-Core` is about Formality-Core so is very outdated. It is necessary to review its content.
* [ ] `tutorial.md` is a Tutorial about Formality-Core. Will we keep it?

**Comment by VictorTaelin** [comment]
I think most of those files are there for historical purposes. Most of the documenting should go to https://docs.formality-lang.org, I think. I don't think we should update EA-TT.md right now. Instead, if we want to do it, we should make a proper, scientific paper about it, but that'll take a lot of time. `tutorial.md` is obsolete, and so on. Perhaps just move the `docs` directory to an archive repository?

**Comment by MaisaMilena** [comment]
I like the idea of creating an archive repository. In this case, all relevant content would be in the Docs (Theory category) and the others on the archive repository. Formality repo will no longer have the `docs` folder, right?

**Comment by VictorTaelin** [comment]
I'll just leave the Archive directory for now since it has images we use in many places and is generally harmless.
