### ISSUE TITLE
Type Checker cannot check open with @ in it

### ISSUE THREAD

**Issue by Derenash** [HigherOrderCO/Kind#221]
### Describe the bug
If I try to typecheck any file with an open on a @, the task never ends.

### To Reproduce
```
let a = {1, 2}
let b = {a, a}
open b@fst as ba
ba.fst
```

### Expected behavior
It should either show an error or open ba.fst and ba.snd to use normally. Instead, the type check never ends.

### Environment (please complete the following information):
 - OS: linux
 - kind@1.0.59

**Comment by VictorTaelin** [comment]
Fixed on c02683661bb523c243a5a70ec6568fd01a6889b4
