### ISSUE TITLE
Conflict with `kind` command related to Kubernetes

### ISSUE THREAD

**Issue by MaisaMilena** [HigherOrderCO/Kind#242]
### Describe the bug
There is a Kubernetes' tool called [`kind`](https://kind.sigs.k8s.io) used to run local Kubernetes clusters using Docker. To execute it we use `kind [command]`. This conflicts with the `kind` command from `kind-lang`.

### To Reproduce
1. Install [`kind`](https://kind.sigs.k8s.io/docs/user/quick-start/#installation) (Kubernetes)
   - I used `brew install kind`
2. Use the command `kind <some_file>.kind` to type check a term on the `base` dir
3. It will display an error about using `kind` from Kubernetes: `kind creates and manages local Kubernetes clusters using Docker container 'nodes'`

Obs: to uninstall `kind` (Kubernetes): `brew uninstall kind`

### Expected behavior
I expect to run `kind-lang` command's when inside `Kind/base` directory.

### Environment (please complete the following information):
 - OS: macOS Big Sur 11.4
 - Kind version: kind-lang@1.0.86

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
