### ISSUE TITLE
Missing dpkg-deb may cause a make error

### ISSUE THREAD

**Issue by sbp** [HigherOrderCO/Kind#261]
The [inclusion](https://github.com/uwu-tech/Kind/blob/71c304f49a495a5a59dc7bfd9203661bdbea5ba0/bin/scm/Makefile#L1) of `kind-scm.deb` as a dependency of `all` in `bin/scm/Makefile` causes an error when building with Chez Scheme [according to the instructions](https://github.com/uwu-tech/Kind/blob/master/INSTALL.md), for systems that do not have `dpkg-deb`.

Note that the actual build is unaffected, because the `dpkg-deb` line comes last. It's just a noisy error message that may cause some people to think that the build has failed:

```
[...]
mkdir -p kind-scm_1.0.1-0_amd64/usr/local/bin/
cp bin/kind-scm kind-scm_1.0.1-0_amd64/usr/local/bin/
dpkg-deb --root-owner-group  --build kind-scm_1.0.1-0_amd64/ bin/kind-scm_1.0.1-0_amd64.deb
make: dpkg-deb: No such file or directory
make: *** [kind-scm.deb] Error 1
```

**Comment by rigille** [comment]
Thanks for the report, this is fixed by 6bf1600
