### ISSUE TITLE
The "read the docs" link on the wiki is broken

### ISSUE THREAD

**Issue by dvberkel** [HigherOrderCO/Kind#262]
### Describe the bug
When opening the wiki and following the [read the docs link][docs] the server can't be found

### To Reproduce
1. Open the [wiki](https://github.com/uwu-tech/Kind/wiki)
2. Follow the link [check it][docs]

### Expected behavior
I expected to bask in the glory of wonderful documentation

### Environment (please complete the following information):
 - Mozilla Firefox 90.0.2 (64-bit)

### Additional context
The read the docs link references "formality". Is this an older name for Kind?

[docs]: https://docs.formality-lang.org/en/latest/

**Comment by rigille** [comment]
Indeed we haven't touched the wiki in a while 🙂 
That's correct Kind used to be called Formality, which feels too austere, the name changed to make it more friendly. What topics would you like to be better documented?

**Comment by dvberkel** [comment]
The README is doing a great job of introducing people to various topics. I just wanted to learn more about Kind in general. So I was poking around to see how things work around here.
