### ISSUE TITLE
Homebrew scheme in OSX is chez

### ISSUE THREAD

**Issue by saludes** [HigherOrderCO/Kind#263]
### Describe the (documentation) bug
In https://github.com/uwu-tech/Kind/blob/master/INSTALL.md#building-from-source
there is a way to install a binary for OSX using homebrew.
The only thing is that that `scheme` binary there is actually `chez`

### Environment (please complete the following information):
 - OS: MacOS BigSur 11.5
 - Kind version: Kind 1.0.89

### Additional context
Maybe suggest to symlink `scheme` to `chez` before continuing?

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
