### ISSUE TITLE
In OSX you actually can install scheme from homebrew

### ISSUE THREAD

**Issue by saludes** [HigherOrderCO/Kind#264]
### Describe the bug
In https://github.com/uwu-tech/Kind/blob/master/INSTALL.md#macos
when saying that for MacOS you must compile **scheme** from source.
I think this is no longer true: I installed from homebrew without problems (besides [that](https://github.com/uwu-tech/Kind/issues/263))

### Environment (please complete the following information):
 - OS: MacOS BigSur 11.5
 - Kind version: kind-scm 1.0.85

**Comment by rigille** [comment]
This will work in some cases, however the brew package is based on the official version and it doesn't support Apple silicon yet. I'm reworking the build system to sidestep those issues and distribute Kind as a single binary executable with no dependencies.

**Comment by rigille** [comment]
The new build system is live ^^
Could you try it to see if it works?

**Comment by saludes** [comment]
> however the brew package is based on the official version and it doesn't support Apple silicon yet.

Weird, because I installed it in my M1 Apple mini.

> Could you try it to see if it works?

Would like to, but I’m on vacation and far from my computer for 1 week.

**Comment by rigille** [comment]
No problem

**Comment by saludes** [comment]
Followed your instructions to install from source. Failed at `make` in step **4** with

```
> make

cd ChezScheme && git submodule init && git submodule update
S'ha registrat el submòdul «bin/scm/ChezScheme» (git@github.com:racket/ChezScheme.git) per al camí «./»
S'ha registrat el submòdul «bin/scm/chez-exe» (git@github.com:rigille/chez-exe.git) per al camí «../chez-exe»
S'està clonant a «/Users/saludes/Desktop/kind-lang/Kind/bin/scm/ChezScheme»...
S'està clonant a «/Users/saludes/Desktop/kind-lang/Kind/bin/scm/chez-exe»...
Camí de submòdul «./»: s'ha agafat «bf49dfbd8c47c759bc2ac99978a0db02b2969578»
Camí de submòdul «../chez-exe»: s'ha agafat «937629ad6cdcec698f0b25d996bb9b01a3b7cce7»
cd ChezScheme && ./configure --pb --kernelobj --disable-curses --disable-iconv --disable-x11
Source in "nanopass" is missing; check out Git submodules using
   git submodule init
   git submodule update
make: *** [scheme/bin/scheme] Error 1
```
I did (this time in **Kind**) :
```
git submodule init
git submodule update
```
and worked.

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
