### ISSUE TITLE
Bug on a cached definition.

### ISSUE THREAD

**Issue by caotic123** [HigherOrderCO/Kind#276]
### Describe the bug :
Sometimes when you create a definition and type-check this definition (therefore, the file will be cached), even if the definition name is correct, the compiler will throw that file is not available.

### To Reproduce :
First, create a file with at least a 2-deepness, for example :
```
  /base
  mkDir Example/Bug
  create_file bug2.kind
```
This file will contain some code like this :
```
Example.Bugs.bug2 : U16
  case "a" as v {
      cons : v.head
      nil : 0#16
  }
```
Now, run this file with : 
```Kind Example.Bugs.bug2 --run```
It might print out a "97".
Moreover, type-check this file using :
```Kind Example.Bugs.bug2```
Finally, try to run this file again, and you'll get a message saying that the definition is not found.

### Expected behavior :
The Example.Bugs.bug2 should execute after being cached.

### Environment:
 - OS: MacOS
 - Kind 1.0.91

### Additional context :
  *In my example there is a circumstance, the definition needs a case expression (with U16 type return) to reproduce the problem.*
  *You can try it directly from the base, the file is at Example/Bugs/bug2*

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
