### ISSUE TITLE
empty string is accepted as a valid identifier

### ISSUE THREAD

**Issue by skybrian** [HigherOrderCO/Kind#279]
In the core syntax, it looks like an empty string is accepted as a valid identifier in most places. (For example, it looks like "! = +123" would parse.)

In [FormCore.js](https://github.com/moonad/FormCoreJS/blob/e4e6776d5f418c192dce9bf3a0b729bd7ec50c96/FormCore.js#L157), the parse_name() function can return an empty string, and the same for [Kind.Core.read.name](https://github.com/uwu-tech/Kind/blob/32fcf01a8c9d8d374c630c24b5b106cda38a47d7/base/Kind/Core.kind#L106). The callers mostly don't check for empty, so it will end up in terms.

(This is from reading the code; I haven't tested it.)

**Comment by skybrian** [comment]
Also, a leading digit is accepted, so I think you could write `!0 = +1; 0`.

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
