### ISSUE TITLE
Add a reference on the wiki to the self types paper

### ISSUE THREAD

**Issue by dvberkel** [HigherOrderCO/Kind#283]
**Context**
I recently got interested in Kind and the design principles behind the language. Working with the language and asking questions in the discussions and the chat works great. I just was hungry for more :smile:

Someone mentioned that there is a paper describing self types. Since this is one of the differentiating aspects of Kind, I think it deserves a more prominent role. My suggestion is to breath some live in the wiki again and link the the article as a reference.

**Alternatives**
One could let people ask the same question in the chat, but this seems redundant.

**Has the feature been requested before?**
Not that I am aware of

**If the feature request is approved, would you be willing to submit a PR?**

Yes, but I checked and I am not yet allowed to edit the wiki

**Comment by rigille** [comment]
Strange I thought anyone could edit the wiki! Me and @MaisaMilena are looking how to enable that. Meanwhile I did upload the paper to Fermat's Library so that the community can illuminate it.
https://fermatslibrary.com/p/e794a376

**Comment by dvberkel** [comment]
I have found the [GitHub documentation](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis) that describes how to enable access for anyone with a GitHub account

In short: you have to disable the "restrict editing to collaborators only" option

**Comment by rigille** [comment]
Thanks, it should be enabled now 🙂

**Comment by dvberkel** [comment]
It is! I will add a page with a link to the article
