### ISSUE TITLE
Using P as a field in a datatype

### ISSUE THREAD

**Issue by Eloitor** [HigherOrderCO/Kind#290]
### Describe the bug
A clear and concise description of what the bug is. You can paste the code and error to help us see the context.

This datatype does not compile:
```
type Test{
  new(P: Nat),
}
```

```
Test: Type

Type mismatch.
- Expected: (:Nat) Type
- Detected: Test
With context:
- Test.Self: Test.Self<P:(:Test) Type> (new:(P:Nat) P(Test.new(P))) P(Test.Self)
- P: (:Test) Type
- : (P:Nat) P(Test.new(P))
- P: Nat

Type mismatch.
- Expected: Nat
- Detected: (:Test) Type
With context:
- P: Nat
- P: (:Test) Type
- new: (P:Nat) P(Test.new(P))
```

### To Reproduce
1. Write the code on `base/Test.kind`
2. Use the command `kind Test`

### Expected behavior

It should compile fine, with output:
```
Test: Type

All terms check.
```

### Environment (please complete the following information):
 - OS: Linux
 - Kind version: kind@1.0.92

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
