### ISSUE TITLE
Kind hangs when trying to run via npm

### ISSUE THREAD

**Issue by kahnclusions** [HigherOrderCO/Kind#301]
### Describe the bug
The usage instructions in the README.md don't seem to work. There's no output and nothing happens, not even the help text or errors.

### To Reproduce
1. `nvm install 16`
2. `npm i -g kind-lang`
3. `kind --help`

Nothing happens. OK try creating a main file:
5. `mkdir -p ~/src/kind-test && cd ~/src/kind-test`
6. 
```bash
cat <<EOT >> Main.kind
Main: IO(Unit)
  IO {
    IO.print("Hello, world!")
  }
EOT
```
5. `kind Main` <-- never finishes, just spins up my fans forever
6. `kind Main --run` <-- also never finishes

### Expected behavior
I expected to at least get some output about what went wrong.

### Environment (please complete the following information):
 - OS: Debian
 - kind@1.0.104

**Comment by rigille** [comment]
Thanks for the report, I reproduced the bug. While we work on this you could revert to version `1.0.100` with `npm i -g kind-lang@1.0.100` as a quickfix.

**Comment by kahnclusions** [comment]
Confiming `1.0.100` does work 👍

**Comment by rigille** [comment]
Does it work in version 1.0.105 too?
