### ISSUE TITLE
Infix Functions / custom binary operator

### ISSUE THREAD

**Issue by ken-okabe** [HigherOrderCO/Kind#310]
I'd like to know about Infix Functions or how to define custom binary operators in Kind. 
[Infix Functions In Haskell](https://wuciawe.github.io/functional%20programming/haskell/2016/07/03/infix-functions-in-haskell.html)

I need to define monad operators `>>=` or pipeline `|>` or function composition `.` freely.

I seached the documents and issues but could not find. Thanks!

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
