### ISSUE TITLE
F64 returning incorrect values

### ISSUE THREAD

**Issue by Derenash** [HigherOrderCO/Kind#341]
### Describe the bug
F64 removes 0s after comma before calculations are made
`1.05 + 1.05 = 3.0`

### To Reproduce
1. Write the code on Test.kind
2. Use the command kind Test --run

### Expected behavior
The program should print 2.1, not 3.0

### Environment (please complete the following information):
 - Ubuntu
 - Kind 1.0.119

### Additional context
`F64.neg(10) returns -0.4375`
`F64.neg(1) returns -4.0`

![image](https://user-images.githubusercontent.com/77352564/167601813-4b0afdd2-75dd-43ab-bb3d-4733b095930f.png)

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
