### ISSUE TITLE
Weird error for invalid function

### ISSUE THREAD

**Issue by nicolas-abril** [HigherOrderCO/Kind#392]
The (incorrect) kind program:
```
One
Two {
  3
}
```
Gives the error
```
Expected `<`:
  2 | Two {
```
This is a bit confusing and unexpected since `<` is not required. Should have better error reporting here like `Expected type annotation or rule for 'One'.`

**Comment by nicolas-abril** [comment]
This comes up in this kind of incorrect program that is missing the `=` between the attribute name and value
```
#kdl_state MyFn.state
MyFn : U60 {
  1
}
```

**Comment by algebraic-dev** [comment]
Improved a lot the error message since 0.3
