### ISSUE TITLE
Kdl compilation genereates needless/unused terms

### ISSUE THREAD

**Issue by nicolas-abril** [HigherOrderCO/Kind#404]
The kind to kdl compiler currently generates code that sometimes contains `let`s that are never used, with an unbound variable, `let`s binding a variable to another (useless indirection) and `dup`s where at least one of the bound variables is unused.

The first two I'm certain it happens and will add some examples later, the third one I'm not so sure, but vaguely remember it happening before.

**Comment by algebraic-dev** [comment]
I think that it could be an optimization pass for all backends not only for KDL.
