### ISSUE TITLE
Prevent erased values from being passed to non-erased arguments

### ISSUE THREAD

**Issue by nicolas-abril** [HigherOrderCO/Kind#409]
If a function has an erased argument and in the body of it's rules it passes that value to a function that has to use it in a non-erased position, currently we just get a misterious runtime error.

There should be a test either in compilation or in the type-checking command that makes sure that this situation does not happen

**Comment by nicolas-abril** [comment]
A short example:
```
FnErased -(n: U60) : U60
FnErased n = FnNonErased n 1

FnNonErased (a: U60) (b: U60) : U60
FnNonErased a b = (+ a b)

Main {
  FnErased 2
}
```
Type checks fine, but on runtime fails with
```
Unbound variable: `n`.
On rule: `(FnErased) = (FnNonErased n 1)`.
```

**Comment by algebraic-dev** [comment]
Fixed
