### ISSUE TITLE
Add a mechanism to make `Kindelia.IO.call` usable

### ISSUE THREAD

**Issue by nicolas-abril** [HigherOrderCO/Kind#418]
We are lacking some way to convert a function name to a kindelia name, and a way to type check the return of the called function.

The first behaviour could be easily hardcoded for this specific function call, but we should have a more systematic way of doing it.

I don't know how to approach the seecond problem for now.

**Comment by steinerkelvin** [comment]
This goes hand in hand with the general problem of handling contract interfaces and also the fact that they are limited — right not, _very_ limited, only allowing flat constructors of numbers. How would you check that on Kind?

Maybe we need that `Kindelia.Contract` type after all. We can then retrieve the U120 name, arguments type, return type etc.

```
Kindelia.IO.call (c: Contract) (args: (Contract.args c))
  : Kindelia.IO (Contract.result c)
```

**Comment by nicolas-abril** [comment]
Didn't think of passing a Contract object here, it's a good idea
