### ISSUE TITLE
First erasure example in readme doesn't parse

### ISSUE THREAD

**Issue by courajs** [HigherOrderCO/Kind#46]
For this source:
```
// main.fm
import Base#

bar(T : Type; x : T) : T
  x

main : Number
  bar(~Number, 42)
```

I get this error with `fm -t`:
```
[PARSE-ERROR]
Unexpected symbol.

I noticed the problem on line 8, col 7, file main.fm:

   4| bar(T : Type; x : T) : T
   5|   x
   6|
   7| main : Number
   8|   bar(~Number, 42)
   9|

But it could have happened a little earlier.
I hope this doesn't affect your deadlines!
```
(The tilde on line 8 is red and underlined)

**Comment by VictorTaelin** [comment]
Fixed, but note the language had a major update right now, so the documentation will be full of broken examples until we review them (probably tomorrow, or next week). You picked a bad time to learn the language, but if you do, feel free to open as many issues as you find!

**Comment by courajs** [comment]
Will do!
