### ISSUE TITLE
Example of using move with recursion?

### ISSUE THREAD

**Issue by courajs** [HigherOrderCO/Kind#48]
I don't know what this means - an example would be really helpful!

> Note: while you can use recursive calls as much as you want, it is wise to treat them as normal variables and use move to pass them to branches. This can be a major optimization in some cases

https://github.com/moonad/Formality/blob/master/DOCUMENTATION.md#recursion

**Comment by VictorTaelin** [comment]
Check how `equal_bits` on [Base.fm](https://github.com/moonad/Base.fm/blob/master/Bits.fm#L143) is sending the own function to both branches. That prevents having to copy it twice per call, which can be significant when the number of calls is large. (Some other functions there should be doing that too, for some reason we forgot.)
