### ISSUE TITLE
Add mutter, setter and getter syntax

### ISSUE THREAD

**Issue by algebraic-dev** [HigherOrderCO/Kind#483]
```
let thing = Thing (Object (V3 0.0 0.0 0.0) (V3 0.0 0.0 0.0))
let thing = !Thing thing .object .pos .x += 10.0         // set
let thing = !Thing thing .object .pos .x @= λx (+ x 1.0) // mut
let thing = !Thing thing .object .pos .x                 // get
```

**Comment by VictorTaelin** [comment]
@Derenash what do you think?

**Comment by Derenash** [comment]
Can I use the get without assigning the value to a variable?
Can I do this?
```
let a = Tup5.new 1 2 3 4 5
let b = Tup5.new 6 5 4 3 (!Tup5 a .snd)
```

or this?
```
let a = Tup5.new 1 2 3 4 5
let b = Tup5.new 5 6 7 8 9
let a = !Tup5 a .snd @= λx (+ (!Tup5 b .snd) x) 
```

**Comment by VictorTaelin** [comment]
Yep. Both of these should work.

**Comment by kungfooman** [comment]
Can someone explain `mutter` in more detail? This is the first time I hear about this concept next to `setter`/`getter`.

Is there anything like that in e.g. C++ or JavaScript?

```js
let thing = !Thing thing .object .pos .x @= λx (+ x 1.0) // mut
```

This seems to be the same as `+= 1`, but also able to create more complex calculations without the tedious `a.b.c.d.e.x = fn(a.b.c.d.e.x)`, simply `a.b.c.d.e.x @= fn`?

**Comment by algebraic-dev** [comment]
Yep, the example I gave in the first comment is similar to `thing.object.pos.x @= (x => x + 1)` or simply `thing.object.pos.x += 1`. The difference is that we are in a functional language and therefore the data is immutable, so something like `!Thing thing .a .b @= f` should be translated into a sequence of mutters like `Thing.a.mut thing (value_ => OtherThing.b.mut value_ f)` instead of a local mutation that would happen in imperative languages.

**Comment by algebraic-dev** [comment]
Changed the setter syntax to:
```
 !Thing thing .object .pos .x = 10
```

**Comment by VictorTaelin** [comment]
That was fast...
