### ISSUE TITLE
String / character parsing and printing is backwards

### ISSUE THREAD

**Issue by courajs** [HigherOrderCO/Kind#55]
Since they're both backwards they cancel out if you're only doing string stuff with literals - but if you attempt to construct character programmatically it becomes clear.
Specifically, the Bits type is little endian - the least significant bit is what can be deconstructed with a top-level case statement. But the parser and the `show` function both treat it as big endian.

```haskell
main : Bits
  'a'
```
```
Bits ✔
(be, b0, b1) => b1((be, b0, b1) => b1((be, b0, b1) => b0((be, b0, b1) => b0((be, b0, b1) => b0((be, b0, b1) => b0((be, b0, b1) => b1((be, b0, b1) => be)))))))
```
So, this looks like 0b1100001, or 97 - ascii 'a'.
But, if you increment it:
```haskell
main : Bits
  inc_bits('a')
```
```
Bits ⚠
(be, b0, b1) => b0((be, b0, b1) => b0((be, b0, b1) => b1((be, b0, b1) => b0((be, b0, b1) => b0((be, b0, b1) => b0((be, b0, b1) => b1((be, b0, b1) => be)))))))
```
Incrementing to 0b0010001 doesn't make sense! But, it is actually incrementing a little-endian integer from 0b1000011 to 0b1000100.

I found this while trying to write a `print_nat` function.

I think I can PR a fix for this in the next few days if no one else does it first

**Comment by VictorTaelin** [comment]
Thanks for the issue! Don't PR to fix this since that will change soon anyway though.

**Comment by VictorTaelin** [comment]
I just updated the language to change the format of String back to Number again. Can you test if this still happens? (It should not since it uses `Number` and `.+.`, but just to be sure.)
