### ISSUE TITLE
JS compiler still missing some terms

### ISSUE THREAD

**Issue by g-guimaraes** [HigherOrderCO/Kind#64]
Given the file:

**HelloWorld.fm**
```haskell
import Base#

main : Number
  1
```

Then we compile with:
```ssh
fm -J HelloWorld/main
```

The output code is:
```javascript
(function(){
  return undefined;
})()
```

I already figured out how to fix it. I'll make a PR right now.

**Comment by VictorTaelin** [comment]
Oh, sorry, I didn't notice you made this PR. I figured the issue at roughly the same time and fixed it. Thanks!
