### ISSUE TITLE
Questions about erasures

### ISSUE THREAD

**Issue by Eloitor** [HigherOrderCO/Kind#70]
1. I was trying to write affine functions where I can copy elements of any type. I ended up making a CopiableType Type:
``` 
T CopiableType<T>
| copiableType(
  copy: T -> Pair(T,T),
  firstProj: (x: T) -> x == pair_fst(__ copy(x));
  secondProj: (x: T) -> x == pair_snd(__ copy(x));
  ) 
```
Using this I can write functions that use x two times.  It would be something like this:
```
foo(X, c: CopiableType(X), x: X): Pair(X,X)
  case c
  | copiableType => c.copy(x)
```
If I wanted to use it more times, foo could accept multiple `CopiableType(X)` , or a `CopiableType(CopiableType(X))`  to copy the copy function lol.
At first It seemed to me that all types are copiable but then realized that erasures can make a Type not copiable.  `CopiableType(X)` itself is not copiable, but without erasures it would be.
My question is if this could be a buildin part of Formality... Only by looking at a Type one can see if it is copiable or not, and if it is, writing a copy function is trivial using pattern matching. This way it won’t be necessary to pass a copy function everywhere you want to use it. The only drawback that I see is that in the current version of Formality the number of times a term can be used is restricted, maybe the number of times a term is used could be part of the Type itself.

2. It is possible to give a term of the type `Not(CopiableType(X))` if X is not copiable?

3. What is the purpose of having the erasure in the Subset type? If I I'm writing a proof using some term of the type ` p: Nat .such_that. IsEven`,  then at some point I would need to use p.snd, right? If I should use a Sigma instead, then why having Subsets?

Thank you

**Comment by VictorTaelin** [comment]
Two questions:

1. Why exactly erasure prevents something from being copiable?

2. How do you copy something like a `Bool -> Bool` function? As far as I know, we can make a copy for any first-order type like bools, lists, and most common datatypes, but not for functions.

About your questions:

1. Intuitively (as in, I'm not sure) I think any algebraic datatype without functions is copiable. The way we've been thinking in making this part of the language is by automatically deriving a `copy : A -> Pair(A,A)` function for any algebraic datatype (i.e., in the same way we could derive `show`, `read` instances).

2. I don't know, that's a great question.

3. It is to prevent affecting the runtime performance by something that should have zero cost, such as imposing type-level restrictions to a type. If you don't plan to run it, you just can use Sigma.

About copy, here is an alternate way to make affine copies:

```javascript
// Allows copying a value many times in an affine setup
T Copy<T> (x: T)
| copy(
  x   : T;
  val : T,
  eql : Equal(T,val,x),
  cpy : Copy(T,x)
  ) : Copy(T,x)
```
That allows you to copy a copyable value as many times as you want without leaving the affine subset. For example, here is a function that returns an infinite list of copies of a copyable value:

```javascript
// Copies a value infinitely many times
copies(n: Nat; cpy: Copy(Nat, n)) : List(Sigma(Nat, (x) => x == n))
  case cpy
  + equal(Nat; n;) as e0 : Equal(Nat, cpy.x, n)
  + equal(Nat; n;) as e1 : Equal(Nat, cpy.x, n)
  | copy =>
    let ceql = cpy.eql :: rewrite Equal(Nat, cpy.val, .) with e0
    let head = sigma(_ (x) => x == n; cpy.val, ceql)
    let tail = main(n; cpy.cpy :: rewrite Copy(Nat, .) with e1)
    cons(_ head, tail)
```

And here is a `Copy` instance for `true`:

```
copy_true : Copy(Bool, true)
  copy(__ true, equal(__), copy_true)
```

**Comment by Eloitor** [comment]
Okay, thanks for your answer.

I assumed that erasures made the data unavailable, now I see that this is not the case and you can use it only in erased positions.

Following your example, 
```
f(x: Bool): Bool
  case x
  | true => false
  | false => true

copy_f : Copy(Bool -> Bool, f)
    copy(__ f, equal(__), copy_f)

useCopyf(cpyf: Copy(Bool -> Bool, f)): Pair(Bool -> Bool, Bool -> Bool)
  case cpyf
  | copy => case cpyf.cpy as ff
  | copy => pair(__ cpyf.val , ff.val)

main useCopyf(copy_f)
```
This type-checked correctly.

**Comment by Eloitor** [comment]
By the way, using your code of copies:
```
copy3n : Copy(Nat, 3n)
    copy(__ 3n, equal(__), copy3n)

main : List(Sigma(Nat, (x) => x == 3n))
copies(3n, copy3n)
```

I get this error
`[ERROR]
Attempted to apply a value that isn't a function.
`
