### ISSUE TITLE
Docs: links in readme are dead

### ISSUE THREAD

**Issue by ComFreek** [HigherOrderCO/Kind#73]
> *Formality is fully compiled to a [400-LOC](https://github.com/moonad/Formality/blob/master/src/fm-net.js) [Interaction-Net Runtime](http://docs.formality-lang.org/en/latest/runtime/Formality-Net.html).*

Both links are dead. I wasn't sure what to link to instead (fm-net.ts?), so I couldn't do a PR :smile:

**Comment by johnchandlerburnham** [comment]
Fixed in 0dad6c4, thanks for reporting this!
