### ISSUE TITLE
I noticed the documenation mentioned effects monads, do notation etc. Is this an escape hatch for calling Evm contracts, get/set memory, or even better, to call embedded evm assembly code directly? 

### ISSUE THREAD

**Issue by julian1** [HigherOrderCO/Kind#78]
The impression created is that Formality is within striking distance of being a practical functional language for the evm. With the massive benefit of simplicity.

What's needed? Another monad instance that exposes the required affects?

**Comment by johnchandlerburnham** [comment]
Yes, we currently have compilation of pure computations to EVM, but for a practical smart contract language we also need to implement effects with an `EthIO` type that the compiler will turn into to the correct EVM instructions.

Our current plan is to do that work as part of (or immediately following) our current push to standardize Formality by implementing it in itself. Once that's done we'll not only have a practical functional language that can compile to the EVM, we'll have a practical functional language **that can run on** the EVM.

**Comment by VictorTaelin** [comment]
It is very close but not quite there yet. The main things that are missing are 

1. An efficient way to implement `let` on fast-mode. And by efficient, I mean that I want to save one last pointer indirection that I didn't manage to yet. In an environment like the EVM where every ADD costs money, that matters a lot.

2. A monadic interpreter. That is easy to do (1 week of work), but I'm waiting for (1) before investing in that.

If we don't have that in time, we'll definitely have at the very least an embed DSL capable of generating efficient EVM code. To be honest, that might be the most practical option, but it is not "special" (you could perfectly do that in Agda) so we've been spending more efforts on the full compilation route.

**Comment by VictorTaelin** [comment]
Formality was refactored, closing this issue for now (but those improvements are still needed).
