### ISSUE TITLE
Doc links broken

### ISSUE THREAD

**Issue by Erhannis** [HigherOrderCO/Kind#83]
From https://github.com/moonad/Formality , clicking on https://docs.formality-lang.org in the description leads to a notification that "We moved to Github!", and clicking on the provided link https://github.com/moonad/Formality/blob/master/DOCUMENTATION.md yields a 404.  So...where's the documentation?

**Comment by johnchandlerburnham** [comment]
Hi, sorry about the broken link, the documentation that previously linked to is here: https://github.com/moonad/Formality/blob/master/OLD_DOCUMENTATION.md

We are currently rewriting to the documentation to reflect the significant changes and improvements we've made to Formality over the past few months. This will be in https://github.com/moonad/Formality/blob/master/README.md and https://github.com/moonad/Formality/blob/master/FMC_SPECIFICATION.md for now, and eventually will be rendered as posts on moonad.org.

I have removed the link to docs.formality-lang.org (and unpinned the post on the Telegram channel), and will update with the moonad.org links when we have things live there.
