### ISSUE TITLE
Undefined reference 'String.concat'

### ISSUE THREAD

**Issue by zijer** [HigherOrderCO/Kind#91]
that example provided in Readme.md in the Introduction section uses String.concat, but trying to run the example results in "undefined reference" error.
fm gives this:
![image](https://user-images.githubusercontent.com/15065054/85213190-b18a8180-b363-11ea-8841-e5194d1cf4be.png)
it seems there is no definition for String.concat on moonad.org:
![image](https://user-images.githubusercontent.com/15065054/85213236-3bd2e580-b364-11ea-95b2-6eceaa2cfbe9.png)
you can use mine if you want
```
String.concat(a:String, b:String) : String
  case a:
  | b;
  | String.cons(a.head, String.concat(a.tail, b));
```

**Comment by VictorTaelin** [comment]
Thank you, we need to add `String.concat` to Prelude.fm of https://github.com/moonad/Moonad.org/blob/master/Prelude.fm

**Comment by VictorTaelin** [comment]
Fixed!
